web-app/Pages/Admin/AddArticle.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using DAL.EF;
using DAL.Models;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Authorization;

namespace sports_hub_portal.Pages.Admin
{
    [Authorize]
    public class AddArticleModel : PageModel
    {
        ILogger<AddArticleModel> _logger;
        ApplicationContext _context;
        [BindProperty]
        public Article Article { get; set; }
        
        public DbSet<Category> Categories { get; set; }

        public DbSet<Team> Teams { get; set; }
        public DbSet<Conference> Conferences { get; set; }
        
        public IEnumerable<Location> Locations { get; set; }
        public AddArticleModel(ILogger<AddArticleModel> logger,ApplicationContext db)
        {
            
            _context = db;
            _logger = logger;
        }
        public void OnGet(int? categoryId)
        {
            if(categoryId == null)
            {
                Conferences = _context.Conferences;
                Locations = _context.Locations;
                Teams = _context.Teams;
            }
            else
            {
                
            }
        }
        public IActionResult OnPost(string photoname)
        {
            Categories = _context.Categories;
            Conferences = _context.Conferences;
            Locations = _context.Locations;
            Teams = _context.Teams;
            if (ModelState.IsValid)
            {
                Article.Location = Locations.First(l => l.Id == Article.LocationId);
                Article.Conference = Conferences.First(l => l.Id == Article.ConferenceId);
                Article.Category = Categories.First(l => l.Id == Article.CategoryId);
                Article.Team = Teams.First(l => l.Id == Article.TeamId);
                var file = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "img", "ArticleImages",photoname);
                if (System.IO.File.Exists(file))
                {
                    var img = new Image { Url = photoname };
                    _context.Images.Add(img);
                    _context.SaveChanges();
                    Article.ImageId = img.Id;
                }
                _context.Articles.Add(Article);
                _context.SaveChanges();
            }
            
            return RedirectToPage("./Articles");
        }
        // added handler
        public IFormFile ArticleImage { get; set; }
        public IActionResult OnPostImageUploadHandlerForArticle() 
        {
            string PhotoName = Guid.NewGuid().ToString() + ArticleImage.FileName.Substring(ArticleImage.FileName.LastIndexOf("."));
            var file = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "img", "ArticleImages", PhotoName);
            using (var fileStream = new FileStream(file, FileMode.Create))
            {
                ArticleImage.CopyTo(fileStream);
            }
            return Content(PhotoName);
        }
        //
    }
}

web-app/Pages/Admin/Articles.cshtml.cs
using System.Linq;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using DAL.EF;
using DAL.Models;
using Microsoft.AspNetCore.Authorization;

namespace sports_hub_portal.Pages.Admin
{
    [Authorize]
    public class ArticleModel : PageModel
    {
        private readonly ILogger<ArticleModel> _logger;
        private readonly ApplicationContext _context;
        public IEnumerable<Article> Articles;
        public DbSet<Conference> Conferences;
        public DbSet<Category> Categories;
        public DbSet<Team> Teams;
        
        public ArticleModel(ILogger<ArticleModel> logger, ApplicationContext db)
        {
            _context = db;
            _logger = logger;
            Articles = _context.Articles;
        }
        public void OnGet(string type)
        {
            if (type == null)
            {
                Articles = _context.Articles.Include(a => a.Conference)
                .Include(a => a.Team)
                .Include(a => a.Location)
                .Include(a => a.Category)
                .Include(a => a.Image)
                .ToList();
            }
            else
            {
                Articles = _context.Articles.Include(a => a.Conference)
                .Include(a => a.Team)
                .Include(a => a.Location)
                .Include(a => a.Category)
                .Include(a => a.Image)
                .ToList().FindAll(x => x.Conference.Name.Contains(type));
                if (Articles.Count() == 0)
                {
                    Articles = _context.Articles.Include(a => a.Conference)
                .Include(a => a.Team)
                .Include(a => a.Location)
                .Include(a => a.Category)
                .Include(a => a.Image)
                .ToList().FindAll(x => x.Team.Name.Contains(type));
                }
                if (Articles.Count() == 0)
                {
                    Articles = _context.Articles.Include(a => a.Conference)
                .Include(a => a.Team)
                .Include(a => a.Location)
                .Include(a => a.Category)
                .Include(a => a.Image)
                .ToList().FindAll(x => x.Public == true && type == "1" ? true : false);
                }
                if (Articles.Count() == 0)
                {
                    Articles = _context.Articles.Include(a => a.Conference)
                .Include(a => a.Team)
                .Include(a => a.Location)
                .Include(a => a.Category)
                .Include(a => a.Image)
                .ToList().FindAll(x => x.Public == false && type == "0" ? true : false);
                }
            }
            Categories = _context.Categories;
            Conferences = _context.Conferences;
            Teams = _context.Teams;
        }
        public IActionResult OnGetUpdate()
        {
            return RedirectToPage();
        }
        public IActionResult OnPostDelete(int id)
        {
            Article article;
            if ((article = _context.Articles.Find(id)) != null)
            {
                _context.Articles.Remove(article);
                _context.SaveChanges();
            }
            else
            {
                _logger.LogError("Delete: No content result");
                return new NoContentResult();
            }
            return RedirectToPage();
        }
        public IActionResult OnPostPublish(int id)
        {
            _context.Articles.Find(id).Public = true;
            _context.SaveChanges();
            return RedirectToPage();
        }
        public IActionResult OnPostUnpublish(int id)
        {
            _context.Articles.Find(id).Public = false;
            _context.SaveChanges();
            return RedirectToPage();
        }
        public IActionResult OnPostTurnOnComments(int id)
        {
            _context.Articles.Find(id).Commentable = true;
            _context.SaveChanges();
            return RedirectToPage();
        }
        public IActionResult OnPostTurnOffComments(int id)
        {
            _context.Articles.Find(id).Commentable = false;
            _context.SaveChanges();
            return RedirectToPage();
        }
        public IActionResult OnPostMoveByCategory(int articleId, int categoryId)
        {
            if (_context.Categories.First(c => c.Id == categoryId) != null)
            {
                
                _context.Articles.Find(articleId).CategoryId = categoryId;
                _context.SaveChanges();
            }
            else
            {
                _logger.LogError($"PostMoveCategory: category with id {categoryId} doesn't exist");
            }
            return RedirectToPage();
        }
    }   
}

web-app/Pages/Admin/EditArticle.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using DAL;
using DAL.EF;
using DAL.Models;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Authorization;

namespace sports_hub_portal.Pages.Admin
{
    [Authorize]
    public class EditArticleModel : PageModel
    {
        ApplicationContext _context;
        ILogger<EditArticleModel> _logger;
        public EditArticleModel(ILogger<EditArticleModel> logger, ApplicationContext db)
        {
            _logger = logger;
            _context = db;
        }
        [BindProperty]
        public Article Article { get; set; }
        public DbSet<Category> Categories { get; set; }
        public DbSet<Conference> Conferences { get; set; }
        public DbSet<Location> Locations { get; set; }
        public DbSet<Team> Teams;
        public void OnGet(int id)
        {
            
            Locations =  _context.Locations;
            Categories = _context.Categories;
            Conferences =_context.Conferences;
            Article = _context.Articles.Find(id);
            Article.Image = _context.Images.Find(Article.ImageId);
            Teams = _context.Teams;
        }
        public IActionResult OnPost(int id, string? photoname)
        {
            var article = _context.Articles.Find(id);
            
            article.LocationId = Article.LocationId;
            article.ConferenceId = Article.ConferenceId;
            article.CategoryId = Article.CategoryId;
            article.Caption = Article.Caption;
            article.Alt = Article.Alt;
            article.Content = Article.Content;
            article.Headline = Article.Headline;
            article.Public = Article.Public;
            article.Commentable = Article.Commentable;
            if(photoname != null)
            {
                var file = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "img", "ArticleImages", photoname);
                if (System.IO.File.Exists(file))
                {
                    var img = new Image { Url = photoname };
                    _context.Images.Add(img);
                    _context.SaveChanges();
                    article.ImageId = img.Id;
                }
            }
            
            _context.SaveChanges();
            return Redirect("./Articles");
        }
        
        public IFormFile ArticleImage { get; set; }
        public IActionResult OnPostImageUploadHandlerForArticle()
        {
            string PhotoName = Guid.NewGuid().ToString() + ArticleImage.FileName.Substring(ArticleImage.FileName.LastIndexOf("."));
            var file = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "img", "ArticleImages", PhotoName);
            using (var fileStream = new FileStream(file, FileMode.Create))
            {
                ArticleImage.CopyTo(fileStream);
            }
            return Content(PhotoName);
        }
    }
}

web-app/Pages/Admin/Articles.cshtml
@page "{type?}"
@model ArticleModel

@section Styles{
    <link rel="stylesheet" href="@Url.Content("~/css/Article.css")">
}

<section>
    <div class="container my-5">
        <div class="row">
            <div class="col-4">
                <div class="row top-dropdown">
                    <button class="top-dropbutton">All Conference</button>
                    <div class="top-droplist">
                        @foreach (var conference in Model.Conferences)
                        {
                            <form method="get">
                                <button type="submit" asp-page-handler="Update" asp-route-type="@conference.Name">
                                    @conference.Name
                                </button>
                            </form>
                        }
                    </div>
                </div>
            </div>

            <div class="col-4">
                <div class="row top-dropdown">
                    <button class="top-dropbutton">All Teams</button>
                    <div class="top-droplist">
                        @foreach (var team in Model.Teams)
                        {
                            <form method="get">
                                <button type="submit" asp-page-handler="Update" asp-route-type="@team.Name">
                                    @team.Name
                                </button>
                            </form>
                        }
                    </div>
                </div>
            </div>

            <div class="col-4">
                <div class="row top-dropdown">
                    <button class="top-dropbutton">All</button>
                    <div class="top-droplist">
                        <form method="get">
                            <button type="submit" asp-page-handler="Update" asp-route-type="1">
                                Published
                            </button>
                            <button type="submit" asp-page-handler="Update" asp-route-type="0">
                                Unpublished
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container articles">
        @foreach (var article in Model.Articles)
        {
            <div class="article">

                <div class="image">
                    <img src="@Url.Content($"~/img/ArticleImages/{article.Image.Url}")" alt="Alt">
                </div>
                <div class="info">
                    <div class="text">
                        <div class="title font-size-huge color-dark-gray"><span>@article.Headline</span></div>
                        <div class="description font-size-large color-gray"><span>@article.Caption</span></div>
                    </div>
                    <div class="status">
                        <div class="teams font-size-large color-gray">
                            @article.Conference.Name / @article.Team.Name
                        </div>
                        @if (article.Public)
                        {
                            <div class="published font-size-medium">
                                Published
                            </div>
                        }
                    </div>
                </div>

                <div class="dropdown right">
                    <button class="dropbtn"><i class="dot"></i><i class="dot"></i><i class="dot"></i></button>
                    <div class="dropdown-content">
                        @if (article.Public)
                        {
                            <form method="post">
                                <button type="submit" asp-page-handler="Unpublish" asp-route-id="@article.Id">Unpublish</button>
                            </form>
                        }
                        else
                        {
                            <form method="post">
                                <button type="submit" asp-page-handler="Publish" asp-route-id="@article.Id">Publish</button>
                            </form>
                        }
                        <a asp-page="EditArticle" asp-route-id="@article.Id">Edit</a>
                        <form method="post">
                            <button type="submit" asp-page-handler="Delete" asp-route-id="@article.Id">Delete</button>
                        </form>
                        <div class="inner-dropdown">
                            <span>Move</span>
                            <div class="dropdown-content">
                                <form method="post">
                                    @foreach (var category in Model.Categories)
                                    {
                                        if (category.Id != article.CategoryId)
                                        {
                                            <button type="submit" asp-page-handler="MoveByCategory" asp-route-articleId="@article.Id" asp-route-categoryId="@category.Id">@category.Name</button>
                                        }
                                    }
                                </form>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        }
    </div>
</section>