web-app/Components/CommentsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Security.Claims;
using DAL.EF;
using sports_hub_portal.Views.Shared.Components.Comments;
using DAL.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using BAL.Managers;
using BAL.Interfaces;

namespace sports_hub_portal.Components
{
    public class CommentsViewComponent : ViewComponent
    {
        private readonly UserManager<ApplicationUser> _userManager;
        public ApplicationContext _applicationContext;
        private readonly ICommentsManager _commentsManager;
        public CommentsViewComponent(ApplicationContext applicationContext, UserManager<ApplicationUser> userManager, ICommentsManager commentsManager) {
            _applicationContext = applicationContext;
            _userManager = userManager;
            _commentsManager = commentsManager;
        }
        
        [AllowAnonymous]
        public async Task<IViewComponentResult> InvokeAsync(int articleId, string sortType = "Recent")
        {
            var currentUser = await _userManager.GetUserAsync((ClaimsPrincipal)User);
            UserProfile userProfile;
            if (currentUser != null)
            {
                userProfile = await _applicationContext.UserProfiles.FindAsync(currentUser.Id);
            }
            else userProfile = null;
            var comments = _commentsManager.GetComments(articleId);
            var obj = new SectionModel()
            {
                currentUser = userProfile,
                comments = _commentsManager.SortComments(sortType, comments),
                replies = comments.Where(x => x.RepliedCommentID != null).ToList(),
                articleId = articleId,
                sortType = sortType
            };
            return View(obj);
        }
    }
}

web-app/Components/MoreArticlesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using DAL.EF;
using Microsoft.AspNetCore.Authorization;
using sports_hub_portal.Views.Shared.Components.MoreArticles;
using System.Linq;
using System;
using Microsoft.EntityFrameworkCore;

namespace sports_hub_portal.Components
{
    public class MoreArticlesViewComponent : ViewComponent
    {
        ApplicationContext db;
        public MoreArticlesViewComponent(ApplicationContext context)
        {
            db = context;
        }

        [AllowAnonymous]
        public IViewComponentResult Invoke(int categoryId)
        {
            var model = new MoreArticlesModel() { Articles = db.Articles.Include(k => k.Image).Where(x => x.CategoryId == categoryId).Take(Math.Min(6, db.Articles.Where(x => x.CategoryId == categoryId).Count())).ToList() };
            return View(model);
        }
    }
}

web-app/Pages/ArticleList.cshtml.cs
using System.Collections.Generic;

using Microsoft.AspNetCore.Mvc.RazorPages;

using DAL.Models;

using BAL.Interfaces;

namespace sports_hub_portal.Pages
{
    public class ArticleListModel : PageModel
    {
        private readonly IArticleManager articleManager;
        public List<Article> articles;

        public ArticleListModel(IArticleManager manager)
        {
            articleManager = manager;
        }

        public void OnGet()
        {
            articles = articleManager.GetArticleList();
        }
    }
}

web-app/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace sports_hub_portal.Pages
{
	[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
	public class ErrorModel : PageModel
	{
		public string RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

		private readonly ILogger<ErrorModel> _logger;

		public ErrorModel(ILogger<ErrorModel> logger)
		{
			_logger = logger;
		}

		public void OnGet()
		{
			RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
		}
	}
}

web-app/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DAL.Models;
using DAL.EF;

namespace sports_hub_portal.Pages
{
	public class IndexModel : PageModel
	{
		private readonly ILogger<IndexModel> _logger;
		public IndexModel(ILogger<IndexModel> logger)
		{
			_logger = logger;
			
		}
		
		public void OnGet()
		{

		}
	}
}

web-app/Pages/PersonalPage.cshtml.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Identity;
using DAL.Models;
using DAL.EF;
using DAL.Services;
using BAL.Interfaces;
using BAL.Services;

namespace sports_hub_portal.Pages
{
    public class UploadModel : PageModel
    {
        private readonly IPersonalInfoManager _personalInfoManager;
        private readonly ISaveImageManager _saveImageService;

        public IFormFile Avatar { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string AvatarName { get; set; }
        public bool ShowNotification { get; set; } = false;
        public bool UpdateResultSuccess { get; set; }
        public bool UpdatedEmail { get; set; }
        public bool EmailExists { get; set; }

        public UploadModel(IPersonalInfoManager personalInfoManager, ISaveImageManager saveImageService) 
        {
            _personalInfoManager = personalInfoManager;
            _saveImageService = saveImageService;
        }
        public async Task OnGet() 
        {
            var userProfile = await _personalInfoManager.GetPersonalAsync(User);
            Email = userProfile.Email;
            FirstName = userProfile.FirstName;
            LastName = userProfile.LastName;
            AvatarName = userProfile.AvatarName;
        }
        public IActionResult OnPostImageUploadHandler() 
        {
            string result = _saveImageService.SaveImage(Avatar, "AvatarUploads");
            if (result is null) 
            {
                result = "";
                Response.StatusCode = 500;
            }
            return Content(result);
        }
        public async Task OnPostUserInfoHandler() 
        {
            ShowNotification = true;
            EmailExists = false;
            string avatarName = string.Empty;
            string firstName = string.Empty;
            string lastName = string.Empty;
            string email = string.Empty;
            try
            {
                avatarName = Request.Form["NewAvatarName"];
                firstName = Request.Form["FirstName"];
                lastName = Request.Form["LastName"];
                email = Request.Form["Email"];
                var userProfile = await _personalInfoManager.GetPersonalAsync(User);
                Email = userProfile.Email;
                FirstName = userProfile.FirstName;
                LastName = userProfile.LastName;
                AvatarName = userProfile.AvatarName;
                if (userProfile.Email != email)
                {
                    var tokenResult =await _personalInfoManager.GenerateEmailChangeVerificationTokenAsync(User, email);
                    if(tokenResult.Token is null)
                        throw new Exception();
                    var link = Url.Action("ChangeEmail", "Account", new { tokenResult.UserId, tokenResult.Token}, protocol: HttpContext.Request.Scheme);
                    EmailService emailService = new EmailService();
                    string confirmationLetter = System.IO.File.ReadAllText("./wwwroot/html/ConfirmationLetter.html").Replace("LINK", link);
                    await emailService.SendEmailAsync(email, "Confirm your account", confirmationLetter);
                    UpdatedEmail = true;
                }
                else
                    UpdatedEmail = false;
                if (!await _personalInfoManager.ChangeNameAsync(User, firstName, lastName))
                    throw new Exception();
                if (avatarName != "")
                {
                    if (!await _personalInfoManager.ChangeAvatarAsync(User, avatarName))
                        throw new Exception();
                }
                UpdateResultSuccess = true;
            }
            catch (Exception)
            {
                UpdateResultSuccess = false;
            }
            finally
            {
                LastName = lastName;
                FirstName = firstName;
                Email = email;
                if (avatarName != "") AvatarName = avatarName;
            }
        }
    }
}

web-app/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace sports_hub_portal.Pages
{
	public class PrivacyModel : PageModel
	{
		private readonly ILogger<PrivacyModel> _logger;

		public PrivacyModel(ILogger<PrivacyModel> logger)
		{
			_logger = logger;
		}

		public void OnGet()
		{
		}
	}
}

web-app/Pages/ViewArticle.cshtml.cs
using System.Collections.Generic;

using Microsoft.AspNetCore.Mvc.RazorPages;

using DAL.Models;

using BAL.Interfaces;

namespace sports_hub_portal.Pages
{
    public class ViewArticleModel : PageModel
    {
        private readonly IArticleManager articleManager;
        public Article articles;

        public ViewArticleModel(IArticleManager manager)
        {
            articleManager = manager;
        }
        public void OnGet(int id)
        {
            articles = articleManager.GetArticle(id);
        }
    }
}

web-app/Pages/ArticleList.cshtml
@page
@model ArticleListModel
@{

}
@section Styles { }

<section>
    <link href="~/css/ArticleList.css" rel="stylesheet" />
    <div class="container my-5">
        @foreach (var articles in Model.articles)
        {
            <a asp-page="ViewArticle" asp-route-id="@articles.Id">
                <div class="row my-5">
                    <div class="col-4">
                        <img src="@Url.Content($"~/img/ArticleImages/{articles.Image.Url}")" alt="Alternate Text" />
                    </div>
                    <div class="col-8">
                        <div class="row article-card-title font-sans">@articles.Headline</div>
                        <div class="row my-4 article-card-text font-sans">
                            <p>
                                @articles.Content
                            </p>
                        </div>
                        <div class="row article-card-text font-sans">@articles.Conference.Name / @articles.Team.Name</div>
                    </div>
                </div>
            </a>
        }
    </div>
    @section scripts {
        <script>
            var p = $('.article-card-text p');
            for (let trigger = 0; trigger < p.length; trigger++) {
                while ($(p[trigger]).outerHeight() > $('.article-card-text').height()) {
                    $(p[trigger]).text(function (index, text) {
                        return text.replace(/\W*\s(\S)*$/, '...');
                    });
                }
            }
        </script>
    }
</section>

web-app/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewBag.Title = "Все пользователи";
}
@section Styles{
    
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

web-app/Pages/PersonalPage.cshtml
@page
@model sports_hub_portal.Pages.UploadModel
@{
    ViewData["title"] = "Personal page";
}
@section Styles {
    <link rel="stylesheet" href="~/css/inputs-and-buttons-styles.css">
}
<section>
    <link rel="stylesheet" href="css/personalPageStyles.css">
    <link rel="stylesheet" href="css/popUpBox.css">
    <link rel="stylesheet" href="css/notificationBox.css">
    @Html.AntiForgeryToken()
    <div id="notification-from-server">
        @if (Model.ShowNotification)
         {
            if (Model.UpdateResultSuccess)
            {
                if (Model.UpdatedEmail)@(await Html.PartialAsync("Notifications/SuccessfullEmailChange.cshtml"))
                else @(await Html.PartialAsync("Notifications/SuccessfullUpdate.cshtml"))
            }
            else
            {
                if(Model.EmailExists)@(await Html.PartialAsync("Notifications/ErrorAccountExists.cshtml"))
                else @(await Html.PartialAsync("Notifications/ErrorUpdate.cshtml"))
            }
         }
    </div>

    @(await Html.PartialAsync("Notifications/ErrorInFieldsUpdate.cshtml"))

    @(await Html.PartialAsync("Notifications/ErrorImageUpload.cshtml"))

    @(await Html.PartialAsync("Shared/_WrongFormatPopUp.cshtml"))

    <div id="personal-page-container" class="row">
        <div class="col-lg-3 personal-page-menu personal-page-menu-active">Personal</div>
        <div class="col-lg-3 personal-page-menu">Change Password</div>
        <div class="col-lg-3 personal-page-menu">My Surveys</div>
        <div class="col-lg-3 personal-page-menu">Team Hub</div>
        <div id="personal-page-avatar-container">
            <div id="image-cropper">
                <img src="~/img/AvatarUploads/@Model.AvatarName" id="personal-page-avatar">
            </div>
            <label for="avatar-upload">
                <img src="~/img/Group156.png" id="avatar-upload-label">
            </label>
            <form method="post" asp-page-handler="ImageUploadHandler" id="submit-avatar" enctype="multipart/form-data">
                <input type="file" id="avatar-upload" asp-for="Avatar" name="Avatar">
            </form>
        </div>
        <div id="input-fields">
            <form id="input-fields-container" method="post" asp-page-handler="UserInfoHandler" onsubmit="return CheckInputs();">
                <input type="hidden" class="form-control personal-page-input-form" name="NewAvatarName" id="avatar-name-input">
                <div class="text-above-input">first name</div>
                <input type="text" class="form-control personal-page-input-form" name="FirstName" id="first-name-input" value="@Model.FirstName">
                <div class="text-above-input">last name</div>
                <input type="text" class="form-control personal-page-input-form" name="LastName" id="last-name-input" value="@Model.LastName">
                <div class="text-above-input">email</div>
                <input type="text" class="form-control personal-page-input-form" name="Email" id="email-input" value="@Model.Email">
                <input type="submit" id="update-profile-button" class="form-control" value="update profile">
            </form>
        </div>
    </div>
    @section scripts{
        <script>
            $('#avatar-upload').on("change", () => {
                let file = $("#avatar-upload")[0].files[0];
                if (file.name.split(".").pop() == "jpeg" || file.name.split(".").pop() == "png" || file.name.split(".").pop() == "tif" || file.name.split(".").pop() == "jpg") {
                    let formdata = new FormData(document.getElementById("submit-avatar"));
                    let csrf = document.getElementsByName('__RequestVerificationToken')[0].value;
                    let data = {
                        method: 'post',
                        headers: {
                            'XSRF-TOKEN': csrf
                        },
                        body: formdata
                    }
                    let url = window.location.href;
                    if (url.includes("?")) url = url.slice(0, url.lastIndexOf('?'));
                    fetch(url + '?handler=ImageUploadHandler', data)
                        .then((res) => res.text())
                        .then((res) => {
                            $('#personal-page-avatar').attr('src', "/img/AvatarUploads/" + res);
                            $('#avatar-name-input').attr('value', res);
                        })
                        .catch((error) => {
                            MakeHidden('notification-about-update');
                            MakeHidden('notification-about-email-update');
                            MakeHidden('notification-about-update-succsess');
                            MakeHidden('notification-about-fields-error');
                            MakeVisible('notification-about-image-upload');
                            console.log(error);
                        });
                }
                else {
                    MakeVisible('wrong-format-pop-up');
                }
            });
            $('#first-name-input').on('change', () => { UncheckedInput('first-name-input') });
            $('#last-name-input').on('change', () => { UncheckedInput('last-name-input') });
            $('#email-input').on('change', () => { UncheckedInput('email-input') });
            $('#ok-button').on('click', () => { MakeHidden('wrong-format-pop-up') });
            $('body').on('click', '#retry', () => {
                $('#input-fields-container').submit();
            })
            function CheckInputs() {
                let result = true;
                let firstName = $('#first-name-input').val();
                let lastName = $('#last-name-input').val();
                let email = $('#email-input').val();
                if (firstName.length == 0 || /\d/.test(firstName)) {
                    InputError('first-name-input');
                    result = false;
                }
                else {
                    InputOk('first-name-input');
                }
                if (lastName.length == 0 || /\d/.test(lastName)) {
                    InputError('last-name-input');
                    result = false;
                }
                else {
                    InputOk('last-name-input');
                }
                const re = /^(([^<>()[\]\\.,;:\s@@"]+(\.[^<>()[\]\\.,;:\s@@"]+)*)|(".+"))@@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/; //email
                if (!re.test(email)) {
                    InputError('email-input');
                    result = false;
                }
                else {
                    InputOk('email-input');
                }
                if (!result) {
                    MakeHidden('notification-about-image-upload');
                    MakeHidden('notification-about-update');
                    MakeHidden('notification-about-email-update');
                    MakeHidden('notification-about-update-succsess');
                    MakeVisible('notification-about-fields-error');
                }
                return result;
            }
            function MakeHidden(elementId) {
                $('#' + elementId).addClass("hidden-element");
            }
            function MakeVisible(elementId) {
                $('#' + elementId).removeClass("hidden-element");
            }
            function InputError(inputId) {
                $('#' + inputId).removeClass("input-ok");
                $('#' + inputId).addClass("input-fail");
            }
            function InputOk(inputId) {
                $('#' + inputId).removeClass("input-fail");
                $('#' + inputId).addClass("input-ok");
            }
            function UncheckedInput(inputId) {
                $('#' + inputId).removeClass('input-ok');
                $('#' + inputId).removeClass('input-fail');
            }
        </script>
    }
</section>

web-app/Pages/ViewArticle.cshtml
@page "{id:int}"
@model ViewArticleModel
@{

}
@section Styles {
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="~/css/view-article.css">
}

<section>
    <div class="container my-5">

        <div class="col">
            <div class="dealbook side-title">@Model.articles.Category.Name</div>
            <div class="news side-title">NEWS</div>
            <!-- Title part -->
            <div class="row">
                <div class="path font-opensans">
                    <a class="gray-path link" href="">@Model.articles.Category.Name</a>
                    <div class="red-path" id="arrow"></div>
                    <span class="red-path">@Model.articles.Headline</span>
                </div>
            </div>

            <!-- Image part -->
            <div class="row my-4">
                <img id="img" src="@Url.Content($"~/img/ArticleImages/{Model.articles.Image.Url}")" alt="">
            </div>

            <!-- Text part -->
            <div class="row my-5 black-text" id="article">
                @Html.Raw(@Model.articles.Content)
            </div>
        </div>

    </div>
    <div id="comment-section">
        @await Component.InvokeAsync("Comments", new { articleId = Model.articles.Id })
    </div>
    @await Component.InvokeAsync("MoreArticles", new { categoryId = Model.articles.CategoryId})
</section>